plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  Exclude:
    - "examples/**/*"

Metrics/MethodLength:
  Max: 35
  Exclude:
    - "spec/**/*"
    - "examples/**/*"

Metrics/AbcSize:
  Max: 45
  Exclude:
    - "spec/**/*"
    - "examples/**/*"

Metrics/ClassLength:
  Max: 220
  Exclude:
    - "spec/**/*"
    - "examples/**/*"

Metrics/CyclomaticComplexity:
  Max: 15
  Exclude:
    - "spec/**/*"

Metrics/PerceivedComplexity:
  Max: 15
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
    - "examples/**/*"

RSpec/ExampleLength:
  Max: 15
  Exclude:
    - "spec/**/*_spec.rb"

RSpec/MultipleExpectations:
  Max: 7
  Exclude:
    - "spec/**/*_spec.rb"

RSpec/MultipleDescribes:
  Enabled: false

# Exclude examples from style checks (they're just examples)
Style/Documentation:
  Exclude:
    - "examples/**/*"

Style/WordArray:
  Exclude:
    - "examples/**/*"

Style/StringConcatenation:
  Exclude:
    - "examples/**/*"

Lint/ScriptPermission:
  Exclude:
    - "examples/**/*"

Lint/AmbiguousOperatorPrecedence:
  Exclude:
    - "examples/**/*"

Layout/TrailingEmptyLines:
  Exclude:
    - "examples/**/*"
