inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: true
  Exclude:
    - "devagent_proper.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  Exclude:
    - "examples/**/*"

Metrics/MethodLength:
  Max: 35
  Exclude:
    - "spec/**/*"
    - "examples/**/*"

Metrics/AbcSize:
  Max: 45
  Exclude:
    - "spec/**/*"
    - "examples/**/*"

Metrics/ClassLength:
  Max: 300
  Exclude:
    - "spec/**/*"
    - "examples/**/*"

Metrics/CyclomaticComplexity:
  Max: 15
  Exclude:
    - "spec/**/*"

Metrics/PerceivedComplexity:
  Max: 15
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
    - "examples/**/*"

RSpec/ExampleLength:
  Max: 15
  Exclude:
    - "spec/**/*_spec.rb"

RSpec/MultipleExpectations:
  Max: 7
  Exclude:
    - "spec/**/*_spec.rb"

RSpec/MultipleDescribes:
  Enabled: false

Style/MultilineBlockChain:
  Exclude:
    - "spec/**/*"

RSpec/DescribeClass:
  Exclude:
    - "spec/ollama/errors_spec.rb"

RSpec/DescribeMethod:
  Exclude:
    - "spec/ollama/client_model_suggestions_spec.rb"

RSpec/DescribedClass:
  Exclude:
    - "spec/ollama/errors_spec.rb"
    - "spec/integration/**/*"

RSpec/SpecFilePathFormat:
  Exclude:
    - "spec/ollama/client_model_suggestions_spec.rb"
    - "spec/integration/**/*"

# Exclude examples from style checks (they're just examples)
Style/Documentation:
  Exclude:
    - "examples/**/*"

Style/WordArray:
  Exclude:
    - "examples/**/*"

Style/StringConcatenation:
  Exclude:
    - "examples/**/*"

Lint/ScriptPermission:
  Exclude:
    - "examples/**/*"

Lint/AmbiguousOperatorPrecedence:
  Exclude:
    - "examples/**/*"

Layout/TrailingEmptyLines:
  Exclude:
    - "examples/**/*"
