plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

RSpec/ExampleLength:
  Max: 15
  Exclude:
    - "spec/**/*_spec.rb"

RSpec/MultipleExpectations:
  Max: 7
  Exclude:
    - "spec/**/*_spec.rb"

RSpec/MultipleDescribes:
  Enabled: false
